# Generated by Django 4.1.3 on 2022-11-10 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customers",
            field=models.ManyToManyField(
                related_name="orders", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
