# Generated by Django 4.1.3 on 2022-11-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_customers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autopart",
            options={"verbose_name_plural": "auto_parts"},
        ),
    ]
